### ISSUE TITLE
Dynamically adding objects to WebPD patch model

### ISSUE THREAD

**Issue by taylorbf** [sebpiq/WebPd#101]
Hi @sebpiq , you mentioned that there is an API for dynamically adding objects to the WebPD patch model from the client side, although maybe undocumented. Could you post a small example of this or point me to a function in the code that could help? Can WebPD calculate the inlets/outlets for a new object or does it get that data from the PD file?

**Comment by sebpiq** [comment]
Hi Ben!
I finally got myself to write some docs for it : https://github.com/sebpiq/WebPd#api
Please have a look and tell me if this is helpful ;) or if you have any comment ...

**Comment by taylorbf** [comment]
Wicked, thanks!
