### ISSUE TITLE
reloading a patch

### ISSUE THREAD

**Issue by nkynde** [sebpiq/WebPd#107]
when you load a patch using the loadPatch method it loads the patch on top of what has previously been loaded resulting in more patches playing simultaneously. is there a method for reloading or loading a different patch without reloading the entire page?

**Comment by sebpiq** [comment]
Hi @nkynde you could destroy the patch and recreate it : 

```javascript
var patch = Pd.loadPatch(patchText)
// ...

function reloadPatch() {
    Pd.destroyPatch(patch)
    patch = Pd.loadPatch(patchText)
}
```

Is that what you mean?

**Comment by nkynde** [comment]
Thank you very much .destroyPatch() is what I have been looking for it is not included in the API documentation

**Comment by sebpiq** [comment]
You're right! I added it to the API doc! Thanks :)
