### ISSUE TITLE
invalid connection 9.1 -> 34.0

### ISSUE THREAD

**Issue by bgenchel** [sebpiq/WebPd#108]
I got a patch load error with the above message. Not sure what it means, or how to remedy. Tips? Advice? Thanks!

**Comment by sebpiq** [comment]
can you send me your patch? I might be able to help then :)

**Comment by bgenchel** [comment]
how do I send it?

**Comment by sebpiq** [comment]
you can send it to me by email : sebpiq@gmail.com

**Comment by sebpiq** [comment]
Hi @bgenchel ! The error in your patch is simply that the second outlet of [vcf~] is not implemented yet in WebPd. I made a new commit which shoudl give clearer error messages for people in the future.

Meanwhile you can replace this with a simple low pass ...
