### ISSUE TITLE
WebPd broken in chrome 53 to 57

### ISSUE THREAD

**Issue by kristoferhagbard** [sebpiq/WebPd#109]
I have found that lop~ in some situations creates a very loud noise in chrome Version 56.0.2924.87 (64-bit) on OSX

Here is an example patch: (don't test with headphones!! :-) )

[Archive.zip](https://github.com/sebpiq/WebPd/files/783160/Archive.zip)

**Comment by sebpiq** [comment]
Yes ... basically WebPd is completely broken with chrome between versions 53 and 57. This is because of this bug which they took ages to fix : https://bugs.chromium.org/p/chromium/issues/detail?id=647974

But I am preparing a completely new version on WebPd getting rid completely of Web Audio :)

**Comment by sergiogranadamoreno** [comment]
@sebpiq :O 

Can't wait for you to do that!

**Comment by sebpiq** [comment]
@sergiogranadamoreno it's well on its way already ;) https://github.com/sebpiq/WebPd/tree/refactor-js

**Comment by kristoferhagbard** [comment]
Looking forward to testing it! keep up the awsome work! (For now I got it working with the Heavy compiler from Enzien)

**Comment by mattdiamond** [comment]
> But I am preparing a completely new version on WebPd getting rid completely of Web Audio

Did you mean getting rid of it just for DSP stuff? I'm checking out that branch and it seems like you're still using a ScriptProcessorNode to handle audio output (which makes sense). That part of the Web Audio API is staying in, right?

**Comment by sebpiq** [comment]
@mattdiamond of course I can't get completely rid of Web Audio :) for now the `ScriptProcessorNode` will have to stay, and in the future, `AudioWorklet`.
For now, `WebPd` is working again with master branch in Chrome, as now most devices have version 57 or more.
