### ISSUE TITLE
Network sending data

### ISSUE THREAD

**Issue by jo-pamo** [sebpiq/WebPd#114]
Hi sebiq thanks so much for your work. It’s been really useful a couple of time.

Right know I was wondering whether there’s a way to use OSC protocol on WebPd, or perhaps you know a way to get data in a patch coming from several devices via node.js?

Thanks in advance

**Comment by theotherjenkutler** [comment]
I am also interested in being able to use netsend and netreceive objects within the browser with node.js. Thank you for your hard work, sebiq.

**Comment by sebpiq** [comment]
Hi @jo-pamo and @theotherjenkutler 

Sorry for being so sloppy with answering questions :sob: 

So netsend and netreceive are a bit out of the scope of the project for now. This said, this being the web, it is very easy (if you know a tiny bit of programming) to send and receive data. WebPd has an API to send / receive data to / from JavaScript : https://github.com/sebpiq/WebPd#pdreceivename-callback .

You can then implement your own websocket server and therefore implement a rudimentary communication with WebPd. I have also made a project, which is unfortnately not maintained anymore by lack of time, but would probably allow you to start with a zero configuration option for implementing a WebSocket server / client : https://github.com/sebpiq/rhizome . You would still have to integrate this with WebPd, and therefore write a tiny bit of code to pass the messages from / to rhizome to / from WebPd. But that shouldn't be complicated.

Hopefully this helps !
