### ISSUE TITLE
Any idea/hints for multi-patches support?

### ISSUE THREAD

**Issue by jonlab** [sebpiq/WebPd#117]
Hi there, 
Great project, thanks for all this hard work!

What would be the best approach for multi-patches support? It is not clear from my tests if WebPD supports this. I need to dig more in the code, but It seems that when I load several patches the output becomes kind of distorted.

Use cases could be :
-several patches, totally independants (each in their own "sandbox"). Think "instancing". Sends and receives could not talk to each other between instances.
-several patches, working together. Sends and receives could talk to each other.
-a mix of both approaches (would require "instanciable/locals" and "static/globals" sends and receives.

Thinking out loud: If not already handled, maybe it could be handled by proper prefixing of send/receive names and then globally instancing each patch...

Any idea welcome...

**Comment by sebpiq** [comment]
Hi @jonlab ! Normally multiple patches should work fine, but as you saw yourself : #68 there's going to be a lot of change anyways. All these use cases will be supported without any problem.
