### ISSUE TITLE
del~ with decimal places

### ISSUE THREAD

**Issue by Reinissance** [sebpiq/WebPd#130]
delay~ with initialvalues with floatingpoint numbers give this error:

ERROR : ERROR AS200: Conversion from type 'f64' to 'i32' requires an explicit cast.
      :
 3009 │ toFloat(130.502), 
      │         ~~~~~~~
      └─ in input.ts(3009,25)

**Comment by sebpiq** [comment]
Ok should be fixed (or at least will be in next release) !

**Comment by sebpiq** [comment]
Thanks for these bug reports ! That's super helpful <3
