### ISSUE TITLE
Failure to install the latest version of WebPd

### ISSUE THREAD

**Issue by qlambert-pro** [sebpiq/WebPd#141]
Running: `npm install -g webpd`
Gives:
```
npm ERR! Cannot set properties of null (setting 'dev')
npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-31T16_59_10_106Z-debug-0.log
```

**Comment by sebpiq** [comment]
Aaah ! Not good ... Is it working with a local install (without `-g`) ?

**Comment by sebpiq** [comment]
@qlambert-pro ok thanks ! 
Then for the next few days it will stay like this while as there is a workaround, then I'll fix it with the next release.

**Comment by qlambert-pro** [comment]
ok

**Comment by fmammoli** [comment]
I am also not able to run the latest release using `npx`. Installing locally works fine thought.
Running `npx webpd@latest -i ...etc` gives:

```
npm WARN reify invalid or damaged lockfile detected
npm WARN reify please re-try this operation once it completes
npm WARN reify so that the damage can be corrected, or perform
npm WARN reify a fresh install with no lockfile if the problem persists.
npm ERR! Cannot destructure property 'package' of 'node.target' as it is null.
```

Maybe it helps to find a workaround.

**Comment by sebpiq** [comment]
Should be fixed now with latest release :)

**Comment by qlambert-pro** [comment]
I can confirm.
