### ISSUE TITLE
demos/simple-gui/simple-gui.html canvas clipped

### ISSUE THREAD

**Issue by coderofsalvation** [sebpiq/WebPd#49]
fix: demos/simple-gui/simple-gui.html the svg#canvas needs 'width:100%' and 'height:100%' 

otherwise it won't render everything (at least in chrome Version 39.0.2171.71 (64-bit))

**Comment by sebpiq** [comment]
Cool! Thanks! Anyways, that demo is kinda legacy ... I hope in the future to get a proper kick ass GUI for WebPd. Probably based on https://github.com/the-grid/the-graph

But I'll apply your fix right now.

**Comment by coderofsalvation** [comment]
cool thanks.
Having a nice editor for PD in the browser would be great.
Did you check this:

http://sebpiq.github.io/WebPd/demos/simple-gui/simple-gui.html

Btw. here are some other cool dataflow editors:

**Comment by coderofsalvation** [comment]
https://github.com/engijs/engi
https://github.com/pboyer/flood
https://github.com/nickretallack/Visual-Language
https://github.com/Gregwar/blocks.js

**Comment by coderofsalvation** [comment]
oh wait, I'm mixing things up here.
I thought I was talking to the maintainer of the nodejs 'port'-module
(which connects to PD).
Forget about what I said :D

hope all is well,

Leon

**Comment by sebpiq** [comment]
Anyways, thanks for this list :)
I'll check out all those alternatives!!!

On Mon, Jan 26, 2015 at 3:01 PM, coderofsalvation <notifications@github.com>
wrote:

> oh wait, I'm mixing things up here.
> I thought I was talking to the maintainer of the nodejs 'port'-module
> (which connects to PD).
> Forget about what I said :D
>
> hope all is well,
>
> Leon
>
> On Mon, Jan 26, 2015 at 2:55 PM, Leon van Kammen <leonvankammen@gmail.com>
> wrote:
>
> > https://github.com/engijs/engi
> > https://github.com/pboyer/flood
> > https://github.com/nickretallack/Visual-Language
> > https://github.com/Gregwar/blocks.js
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71464350>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by coderofsalvation** [comment]
np :)

btw. just stumbled upon this, ever seen this? :

http://sebpiq.github.io/pd-fileutils/randomDrone.html

it seems to be part of this javascript package:

https://www.npmjs.com/package/pd-fileutils

**Comment by sebpiq** [comment]
Yeah, its mine :)

On Wed, Jan 28, 2015 at 11:58 AM, coderofsalvation <notifications@github.com
> wrote:

> np :)
>
> btw. just stumbled upon this, ever seen this? :
>
> http://sebpiq.github.io/pd-fileutils/randomDrone.html
>
> it seems to be part of this javascript package:
>
> https://www.npmjs.com/package/pd-fileutils
>
> On Tue, Jan 27, 2015 at 10:41 AM, Sebastien Piquemal <
> notifications@github.com> wrote:
>
> > Anyways, thanks for this list :)
> > I'll check out all those alternatives!!!
> >
> > On Mon, Jan 26, 2015 at 3:01 PM, coderofsalvation <
> > notifications@github.com>
> > wrote:
> >
> > > oh wait, I'm mixing things up here.
> > > I thought I was talking to the maintainer of the nodejs 'port'-module
> > > (which connects to PD).
> > > Forget about what I said :D
> > >
> > > hope all is well,
> > >
> > > Leon
> > >
> > > On Mon, Jan 26, 2015 at 2:55 PM, Leon van Kammen <
> > leonvankammen@gmail.com>
> > > wrote:
> > >
> > > > https://github.com/engijs/engi
> > > > https://github.com/pboyer/flood
> > > > https://github.com/nickretallack/Visual-Language
> > > > https://github.com/Gregwar/blocks.js
> > > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71464350>.
> > >
> >
> >
> >
> > --
> >
> > *Sébastien Piquemal*
> >
> > -----* @sebpiq*
> > ----- http://github.com/sebpiq
> > ----- http://funktion.fm
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71616902>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71815684>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by coderofsalvation** [comment]
ah ok :)
in that case, keep up the good work :D

**Comment by coderofsalvation** [comment]
don't know if you already checked this, but just in case:

https://enzienaudio.com
https://enzienaudio.com/dev/api.html

**Comment by sebpiq** [comment]
Yeah, they are friends. Plus the patch rendering is provided by me :)
https://github.com/sebpiq/pd-fileutils

On Wed, Feb 18, 2015 at 9:28 PM, coderofsalvation <notifications@github.com>
wrote:

> don't know if you already checked this, but just in case:
>
> https://enzienaudio.com
> https://enzienaudio.com/dev/api.html
>
> On Wed, Jan 28, 2015 at 3:18 PM, Leon van Kammen <leonvankammen@gmail.com>
>
> wrote:
>
> > ah ok :)
> > in that case, keep up the good work :D
> >
> > On Wed, Jan 28, 2015 at 3:13 PM, Sebastien Piquemal <
> > notifications@github.com> wrote:
> >
> >> Yeah, its mine :)
> >>
> >> On Wed, Jan 28, 2015 at 11:58 AM, coderofsalvation <
> >> notifications@github.com
> >> > wrote:
> >>
> >> > np :)
> >> >
> >> > btw. just stumbled upon this, ever seen this? :
> >> >
> >> > http://sebpiq.github.io/pd-fileutils/randomDrone.html
> >> >
> >> > it seems to be part of this javascript package:
> >> >
> >> > https://www.npmjs.com/package/pd-fileutils
> >> >
> >> > On Tue, Jan 27, 2015 at 10:41 AM, Sebastien Piquemal <
> >> > notifications@github.com> wrote:
> >> >
> >> > > Anyways, thanks for this list :)
> >> > > I'll check out all those alternatives!!!
> >> > >
> >> > > On Mon, Jan 26, 2015 at 3:01 PM, coderofsalvation <
> >> > > notifications@github.com>
> >> > > wrote:
> >> > >
> >> > > > oh wait, I'm mixing things up here.
> >> > > > I thought I was talking to the maintainer of the nodejs
> >> 'port'-module
> >> > > > (which connects to PD).
> >> > > > Forget about what I said :D
> >> > > >
> >> > > > hope all is well,
> >> > > >
> >> > > > Leon
> >> > > >
> >> > > > On Mon, Jan 26, 2015 at 2:55 PM, Leon van Kammen <
> >> > > leonvankammen@gmail.com>
> >> > > > wrote:
> >> > > >
> >> > > > > https://github.com/engijs/engi
> >> > > > > https://github.com/pboyer/flood
> >> > > > > https://github.com/nickretallack/Visual-Language
> >> > > > > https://github.com/Gregwar/blocks.js
> >> > > > >
> >> > > > >
> >> > > >
> >> > > > —
> >> > > > Reply to this email directly or view it on GitHub
> >> > > > <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71464350
> >.
> >> > > >
> >> > >
> >> > >
> >> > >
> >> > > --
> >> > >
> >> > > *Sébastien Piquemal*
> >> > >
> >> > > -----* @sebpiq*
> >> > > ----- http://github.com/sebpiq
> >> > > ----- http://funktion.fm
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71616902>.
> >> > >
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71815684>.
> >> >
> >>
> >>
> >>
> >> --
> >>
> >> *Sébastien Piquemal*
> >>
> >> -----* @sebpiq*
> >> ----- http://github.com/sebpiq
> >> ----- http://funktion.fm
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <https://github.com/sebpiq/WebPd/issues/49#issuecomment-71840275>.
>
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/49#issuecomment-74930583>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm
