### ISSUE TITLE
Browser tests all failing on firefox

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/WebPd#59]

**Comment by WnP** [comment]
works here on firefox 38.0.1

**Comment by sebpiq** [comment]
Strange, it fails for me on ff 38.0.0 and ff 41 on Ubuntu. What OS are you using?

**Comment by toolness** [comment]
They're failing for me on ff 39.0 on OS X, but not all of them--`dsp.phasor~`, `dsp.noise~`, `dsp.delwrite~/delread~`, and a few others all succeed, but a bunch of others fail.

**Comment by sebpiq** [comment]
Yeah ... There is a bunch of Web Audio API bugs in firefox which explain
that it doesn't work great. But there might be also some real bugs ... But
since it doesn't run at all for me on Ubuntu, it is hard to untangle this.
I'll leave the issue open for the moment, and I'll come back to it later.

On Fri, Jul 24, 2015 at 10:54 PM, Atul Varma <notifications@github.com>
wrote:

> They're failing for me on ff 39.0 on OS X, but not all of them--
> dsp.phasor~, dsp.noise~, dsp.delwrite~/delread~, and a few others all
> succeed, but a bunch of others fail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/59#issuecomment-124719835>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm
