### ISSUE TITLE
vague "Uncaught Error: unknown object 0" in console

### ISSUE THREAD

**Issue by plush2** [sebpiq/WebPd#60]
I have a patch that as near as I can tell should work. All objects are present in the supported list, there are 2 abstractions and 2 subpatches. I've been stabbing around in the dark trying to determine what "object 0" could possibly be.

**Comment by sebpiq** [comment]
Could you please send me you patch and abstractions? I'll see what's wrong and fix this error message. Thanks!

**Comment by r-b-g-b** [comment]
I've been getting this message as well. Here's a minimal example that shows it... [webpd-test](https://github.com/r-b-g-b/webpd-test)
Thanks for WebPd--it's a really great tool!

**Comment by sebpiq** [comment]
Ok, I'll have a look!

**Comment by sebpiq** [comment]
@r-b-g-b yes, got it ... this is this bug : https://github.com/sebpiq/pd-fileutils/issues/20  Basically right now I don't support custom size for objects (you had changed the size of your floatatoms). I made a pull request to your code, if you merge it it should work fine now. I'll work on the bug now as well, so this shouldn't happen again in the future!

**Comment by sebpiq** [comment]
Also @plush2 it would be great if you could send me something so I could look into it, and if it is a bug fix it ... thanks!!!

**Comment by r-b-g-b** [comment]
@sebpiq Amazing, thanks so much for your quick reply!

**Comment by plush2** [comment]
I've managed to put an example of an "invalid outlet 0" error up here, [webpd-experiments](https://github.com/plush2/webpd-experiments). I sent some examples over email as well but I figured I should post something here as well.

Thanks for keeping the development of a pd for web audio api going.

**Comment by sebpiq** [comment]
@r-b-g-b you're welcome!
@plush2 thanks for this! I got the mail too. I'll have a look at it in the next couple of days!

**Comment by sebpiq** [comment]
Fixed now! Thanks to you guys @plush2 @r-b-g-b I fixed 2 bugs :D so keep on using WebPd and sending me errors to help me make it better!
