### ISSUE TITLE
"test/browser/dsp/+~-~*~-tests.js" doesn't exist on Windows git checkouts

### ISSUE THREAD

**Issue by toolness** [sebpiq/WebPd#64]
When I run `npm run test.browser.build` on Windows, I get the following error in the gulp output:

```
Cannot find module './+~-~*~-tests.js' from 'C:\WebPd\test\browser\dsp'
```

It looks like this is because [`test/browser/dsp/+~-~*~-tests.js`](https://github.com/sebpiq/WebPd/blob/master/test/browser/dsp/%2B~-~*~-tests.js) simply **doesn't exist** in my checkout. I suspect that this is because `*` is a forbidden character in DOS/Windows filenames.

Can this file be renamed in some way? Maybe to `+~-~asterisk~-tests.js` or something?

**Comment by sebpiq** [comment]
hmm strange!!! What happens if you download the file manually, rename it to something else, update the name of the imported tests [from here](https://github.com/sebpiq/WebPd/blob/master/test/browser/dsp/index.js#L8) and try to run the tests? I'd like to be sure that the name is indeed the problem.

**Comment by toolness** [comment]
Ah, good idea--I just did that and it worked!

I can issue a PR if you want, just let me know what you want the new file name to be.

**Comment by sebpiq** [comment]
That would be great! We can go for `arithm-tests.js` instead of `+~-~*~-tests.js`. But I think I will reorganize these tests in the future. But for the moment this renaming will do the trick! Thanks a lot
