### ISSUE TITLE
tests fail on node 0.12

### ISSUE THREAD

**Issue by toolness** [sebpiq/WebPd#67]
I didn't report this before because I thought it might be Windows-only, but now I'm trying it on an OS X system and I'm getting the same error when running `npm test`:

```
> WebPd@0.3.1 test /Users/atul/Documents/github/WebPd
> mocha --reporter list --recursive test/src

child_process: customFds option is deprecated, use stdio instead.
/WebPd/node_modules/pd-fileutils/node_modules/d3/node_modules/jsdom/lib/jsdom/level1/core.js:418
  set nodeName() { throw new core.DOMException();},
               ^
SyntaxError: Unexpected token )
```

I'm using Node 0.12.7 and npm 2.11.3.

**Comment by sebpiq** [comment]
Yes ... that might be because node 0.12 breaks quite a few things. For the
moment I'd recommend testing with 0.10. You can install several node
versions and switch between them easily by using nvm. I'll open an issue
about that.

On Fri, Jul 24, 2015 at 10:47 PM, Atul Varma <notifications@github.com>
wrote:

> I didn't report this before because I thought it might be Windows-only,
> but now I'm trying it on an OS X system and I'm getting the same error when
> running npm test:
>
> > WebPd@0.3.1 test /Users/atul/Documents/github/WebPd
> > mocha --reporter list --recursive test/src
>
> child_process: customFds option is deprecated, use stdio instead.
> /WebPd/node_modules/pd-fileutils/node_modules/d3/node_modules/jsdom/lib/jsdom/level1/core.js:418
>   set nodeName() { throw new core.DOMException();},
>                ^
> SyntaxError: Unexpected token )
>
> I'm using Node 0.12.7 and npm 2.11.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/67>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by toolness** [comment]
Ah, ok. Would you accept PRs that make everything work on Node 0.12, or do you prefer to stay with 0.10 for now?

**Comment by sebpiq** [comment]
Absolutely!!! It'd be awesome if you could fix it and make a pull
request!!! Looking forward to it :)

On Sat, Jul 25, 2015 at 9:30 AM, Atul Varma <notifications@github.com>
wrote:

> Ah, ok. Would you accept PRs that make everything work on Node 0.12, or do
> you prefer to stay with 0.10 for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/67#issuecomment-124816330>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by toolness** [comment]
Ok! I just submitted sebpiq/pd-fileutils#27 which fixes all the tests in this project.

(I also submitted sebpiq/pd-fileutils#26, which makes all of that project's tests work in Windows :bowtie:)

**Comment by sebpiq** [comment]
merged!
