### ISSUE TITLE
The future of WebPd

### ISSUE THREAD

**Issue by lzref** [sebpiq/WebPd#68]
Hello.

First let me express my admiration for the amazing work you've done. An amazing idea of marrying PureData and web, good development practices, many PD objects already implemented.

I looked through the examples folder and I noticed they weren't interactive (they're just compiled to SVG). Now of course this is a work in progress but I was wondering what kind of vision you have for it. If you had unlimited amount of time and resources what would you like to see as a result? A web player for pd patches where people can upload any pd file (being able to share a URL would be so awesome) and run it? A full scale patch editor that allows to do everything PureData can do but in a browser? Maybe a fork of PureData with improved behavior, different set of objects?

In any case, this sounds incredible. JavaScript and web technologies could solve PureData's problem of ugly and hard to use GUI's. It can become really easy to share the output (audio, visual performances, etc.) with other people, regardless of what platform they're on, whether they have PureData installed or whether they even know what that is.

Keep up the great work!

**Comment by sebpiq** [comment]
Sorry for the very slow answer, busy summer ...

First, thanks very much for this message. I think pretty much all the things you've mentioned are on my wishlist : 

- Web-based Pd graphical interface : which could easily be much better than the desktop graphical interface, more easy to customize and update ..., and a nice tool to share and display patches.
- Better Pd objects which improve some of the annoying things in Pd, which might help pushing Pd forward.

However, as you rightly guessed, I simply lack of time, even to give the core of WebPd the attention it would deserve. All these great ambitions are caught back by reality, and I end-up doing work on WebPd mostly when I need it myself for a project I am working on.

The second issue is the fact that Web Audio API (which is the technology that allows to do audio synthesis in the web browser, and basically made WebPd possible), simply doesn't cut it at the moment. In the future, things might become easier, but I believe it will still take a few years before it's possible to replicate most of Pd's audio functionalities, and reach performance that would be somewhat similar.

This said, I've received messages similar to yours from many different people, so there seems to really be people interested in seeing this happen. WebPd is an open-source project, and I think I have been quite bad so far at trying to get more people to contribute. But I will open a website, a discussion group, mailing list or something ... (google groups? facebook? ...), and hopefully this could help to build a community, and gather a critical mass of developers which could help this to happen.
