### ISSUE TITLE
Which license should WebPd use?

### ISSUE THREAD

**Issue by jeffbonhag** [sebpiq/WebPd#76]
`COPYING` and `COPYING.LESSER` specify GPL and LGPL for the license, and `package.json` says 'Standard Improved BSD License'.

Which is correct?  Let me know and I'll submit a pull request.

**Comment by sebpiq** [comment]
I'll see with @chr15m cause I have even forgotten what license we use exactly ...

**Comment by jeffbonhag** [comment]
:+1:

**Comment by thisconnect** [comment]
Same as Pd would be nice
