### ISSUE TITLE
There is only a 'beep' on Pd.start(), then nothing. And no error info in chrome console.

### ISSUE THREAD

**Issue by Avant-Contra** [sebpiq/WebPd#80]
Hi @sebpiq ,

I made a demo here:
http://chaostao.org/pd/
pd file:
http://chaostao.org/pd/patches/chaos_0.925_without_tab.pd

It is supposed to compute midi sequences and then play sound.You can download the pd file and play it in Pd vanilla.
There is only a 'beep' on Pd.start(), but I'm not sure where the error/bug is, because there is no error info in chrome console. 
But there is a warning in firefox console:
"mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create"
Would this warning cause the problem?

Thanks!

Contra

**Comment by sebpiq** [comment]
I've found the problem. There seems to be a bug with toggle. If you replace the toggle in your patch by a message instead `[1(` to start the `[metro]` on load it works fine.

I'll fix the bug now!

**Comment by Avant-Contra** [comment]
Oh cool, I replaced the toggle with a message instead [1( , and it works fine ~

**Comment by sebpiq** [comment]
Ok, now it is fixed! The new build https://github.com/sebpiq/WebPd/tree/master/dist shouldn't have the bug anymore

**Comment by Avant-Contra** [comment]
Great!!

**Comment by sebpiq** [comment]
Nice patch by the way :)
