### ISSUE TITLE
WebPd Broken with mobile safari update

### ISSUE THREAD

**Issue by ablanton** [sebpiq/WebPd#81]
Hi Everyone,

First amazing work! this project is spectacular. I had a prototype up and running on my phone a week ago and everything is seamless.

I updated mobile safari two days ago and now my prototype is not working. I'm not sure where this issue is coming from but if I can be of any help please let me know! I look forward to working with webPd substantially in the future.

**Comment by sebpiq** [comment]
Hi @ablanton !
I think there was mention on the web audio slack group of a new bug in Safari on iOS9, which would cause the audio to not start at all.
At first, I didn't really take it seriously, but I guess it might real :)
I'll have a chat with other people that had this same issue, and see how to fix it.

**Comment by ablanton** [comment]
Great Sebastien,

Let me know if I can be of any help, I'm not that great with the inner
workings of audio in JS but I really like this project. I know audio is
working in p5 on iOS9, it might be helpful to look at their implementation
strategy.

On Tue, Oct 13, 2015 at 2:39 AM, Sebastien Piquemal <
notifications@github.com> wrote:

> Hi @ablanton <https://github.com/ablanton> !
> I think there was mention on the web audio slack group of a new bug in
> Safari on iOS9, which would cause the audio to not start at all.
> At first, I didn't really take it seriously, but I guess it might real :)
> I'll have a chat with other people that had this same issue, and see how
> to fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-147664178>.
>



-- 
åπ∆®£w °ı• ß|ªπ†°n
andrewblanton.com

**Comment by notthetup** [comment]
Here's the relevant 'bug' from in WebKit. https://bugs.webkit.org/show_bug.cgi?id=149367

**Comment by sebpiq** [comment]
Ok, I added the fix to the examples. @ablanton could you confirm that any of the examples would run on your phone? I don't have an iOS 9 device at hand to do some testing! 

You can try with this one for example : http://sebpiq.github.io/WebPd/examples/phasor/
or this one ; http://sebpiq.github.io/WebPd/examples/delays/

**Comment by ablanton** [comment]
Hi Sebastien,

It's still getting caught on page load. It just says loading, and this is
similar behavior in mobile chrome. Works well on a regular browser, did you
test against older versions of mobile safari?

On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
notifications@github.com> wrote:

> Ok, I added the fix to the examples. @ablanton
> <https://github.com/ablanton> could you confirm that any of the examples
> would run on your phone? I don't have an iOS 9 device at hand to do some
> testing!
>
> You can try with this one for example :
> http://sebpiq.github.io/WebPd/examples/phasor/
> or this one ; http://sebpiq.github.io/WebPd/examples/delays/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831>.
>



-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>

**Comment by sebpiq** [comment]
Oh Wait! So you mean you don't even see the "start" button? It crashes on
"loading"?

On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
notifications@github.com> wrote:

> Hi Sebastien,
>
> It's still getting caught on page load. It just says loading, and this is
> similar behavior in mobile chrome. Works well on a regular browser, did you
> test against older versions of mobile safari?
>
> On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> notifications@github.com> wrote:
>
> > Ok, I added the fix to the examples. @ablanton
> > <https://github.com/ablanton> could you confirm that any of the examples
> > would run on your phone? I don't have an iOS 9 device at hand to do some
> > testing!
> >
> > You can try with this one for example :
> > http://sebpiq.github.io/WebPd/examples/phasor/
> > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831>.
> >
>
>
>
> --
>
> andrewblanton.com
>
> <http://andrewblanton.com/portfolio.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by ablanton** [comment]
yes exactly, like (and correct me if i'm wrong) it is stuck on Pd.start()
on mobile and cannot proceed to load anymore of the page.

On Sun, Oct 18, 2015 at 11:45 AM, Sebastien Piquemal <
notifications@github.com> wrote:

> Oh Wait! So you mean you don't even see the "start" button? It crashes on
> "loading"?
>
> On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
> notifications@github.com> wrote:
>
> > Hi Sebastien,
> >
> > It's still getting caught on page load. It just says loading, and this is
> > similar behavior in mobile chrome. Works well on a regular browser, did
> you
> > test against older versions of mobile safari?
> >
> > On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> > notifications@github.com> wrote:
> >
> > > Ok, I added the fix to the examples. @ablanton
> > > <https://github.com/ablanton> could you confirm that any of the
> examples
> > > would run on your phone? I don't have an iOS 9 device at hand to do
> some
> > > testing!
> > >
> > > You can try with this one for example :
> > > http://sebpiq.github.io/WebPd/examples/phasor/
> > > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831>.
> > >
> >
> >
> >
> > --
> >
> > andrewblanton.com
> >
> > <http://andrewblanton.com/portfolio.html>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701>.
> >
>
>
>
> --
>
> *Sébastien Piquemal*
>
> -----* @sebpiq*
> ----- http://github.com/sebpiq
> ----- http://funktion.fm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037845>.
>



-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>

**Comment by sebpiq** [comment]
No actually if it is stuck on "loading" and you don't even get the start
button, it means it is stuck before `Pd.start` ... That is weird.

What about now, is it working? If not, I'll have to get an ios9 device next
week, and see what's wrong ...

On Sun, Oct 18, 2015 at 9:48 PM, åπ∆®£w °ı• ß|ªπ†°n <
notifications@github.com> wrote:

> yes exactly, like (and correct me if i'm wrong) it is stuck on Pd.start()
> on mobile and cannot proceed to load anymore of the page.
>
> On Sun, Oct 18, 2015 at 11:45 AM, Sebastien Piquemal <
>
> notifications@github.com> wrote:
>
> > Oh Wait! So you mean you don't even see the "start" button? It crashes on
> > "loading"?
> >
> > On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
> > notifications@github.com> wrote:
> >
> > > Hi Sebastien,
> > >
> > > It's still getting caught on page load. It just says loading, and this
> is
> > > similar behavior in mobile chrome. Works well on a regular browser, did
> > you
> > > test against older versions of mobile safari?
> > >
> > > On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> > > notifications@github.com> wrote:
> > >
> > > > Ok, I added the fix to the examples. @ablanton
> > > > <https://github.com/ablanton> could you confirm that any of the
> > examples
> > > > would run on your phone? I don't have an iOS 9 device at hand to do
> > some
> > > > testing!
> > > >
> > > > You can try with this one for example :
> > > > http://sebpiq.github.io/WebPd/examples/phasor/
> > > > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831>.
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > andrewblanton.com
> > >
> > > <http://andrewblanton.com/portfolio.html>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701>.
> > >
> >
> >
> >
> > --
> >
> > *Sébastien Piquemal*
> >
> > -----* @sebpiq*
> > ----- http://github.com/sebpiq
> > ----- http://funktion.fm
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037845>.
> >
>
>
>
> --
>
> andrewblanton.com
>
> <http://andrewblanton.com/portfolio.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037981>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by ablanton** [comment]
unfortunately the problem persist...

On Sun, Oct 18, 2015 at 1:15 PM, Sebastien Piquemal <
notifications@github.com> wrote:

> No actually if it is stuck on "loading" and you don't even get the start
> button, it means it is stuck before `Pd.start` ... That is weird.
>
> What about now, is it working? If not, I'll have to get an ios9 device next
> week, and see what's wrong ...
>
> On Sun, Oct 18, 2015 at 9:48 PM, åπ∆®£w °ı• ß|ªπ†°n <
>
> notifications@github.com> wrote:
>
> > yes exactly, like (and correct me if i'm wrong) it is stuck on Pd.start()
> > on mobile and cannot proceed to load anymore of the page.
> >
> > On Sun, Oct 18, 2015 at 11:45 AM, Sebastien Piquemal <
> >
> > notifications@github.com> wrote:
> >
> > > Oh Wait! So you mean you don't even see the "start" button? It crashes
> on
> > > "loading"?
> > >
> > > On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
> > > notifications@github.com> wrote:
> > >
> > > > Hi Sebastien,
> > > >
> > > > It's still getting caught on page load. It just says loading, and
> this
> > is
> > > > similar behavior in mobile chrome. Works well on a regular browser,
> did
> > > you
> > > > test against older versions of mobile safari?
> > > >
> > > > On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> > > > notifications@github.com> wrote:
> > > >
> > > > > Ok, I added the fix to the examples. @ablanton
> > > > > <https://github.com/ablanton> could you confirm that any of the
> > > examples
> > > > > would run on your phone? I don't have an iOS 9 device at hand to do
> > > some
> > > > > testing!
> > > > >
> > > > > You can try with this one for example :
> > > > > http://sebpiq.github.io/WebPd/examples/phasor/
> > > > > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831
> >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > andrewblanton.com
> > > >
> > > > <http://andrewblanton.com/portfolio.html>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701>.
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > *Sébastien Piquemal*
> > >
> > > -----* @sebpiq*
> > > ----- http://github.com/sebpiq
> > > ----- http://funktion.fm
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037845>.
> > >
> >
> >
> >
> > --
> >
> > andrewblanton.com
> >
> > <http://andrewblanton.com/portfolio.html>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037981>.
>
> >
>
>
>
> --
>
> *Sébastien Piquemal*
>
> -----* @sebpiq*
> ----- http://github.com/sebpiq
> ----- http://funktion.fm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149043402>.
>



-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>

**Comment by sebpiq** [comment]
Dammit ... ok I'll find a device and solve this.

On Mon, Oct 19, 2015 at 12:31 AM, åπ∆®£w °ı• ß|ªπ†°n <
notifications@github.com> wrote:

> unfortunately the problem persist...
>
>
> On Sun, Oct 18, 2015 at 1:15 PM, Sebastien Piquemal <
> notifications@github.com> wrote:
>
> > No actually if it is stuck on "loading" and you don't even get the start
> > button, it means it is stuck before `Pd.start` ... That is weird.
> >
> > What about now, is it working? If not, I'll have to get an ios9 device
> next
> > week, and see what's wrong ...
> >
> > On Sun, Oct 18, 2015 at 9:48 PM, åπ∆®£w °ı• ß|ªπ†°n <
> >
> > notifications@github.com> wrote:
> >
> > > yes exactly, like (and correct me if i'm wrong) it is stuck on
> Pd.start()
> > > on mobile and cannot proceed to load anymore of the page.
> > >
> > > On Sun, Oct 18, 2015 at 11:45 AM, Sebastien Piquemal <
> > >
> > > notifications@github.com> wrote:
> > >
> > > > Oh Wait! So you mean you don't even see the "start" button? It
> crashes
> > on
> > > > "loading"?
> > > >
> > > > On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
> > > > notifications@github.com> wrote:
> > > >
> > > > > Hi Sebastien,
> > > > >
> > > > > It's still getting caught on page load. It just says loading, and
> > this
> > > is
> > > > > similar behavior in mobile chrome. Works well on a regular browser,
> > did
> > > > you
> > > > > test against older versions of mobile safari?
> > > > >
> > > > > On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> > > > > notifications@github.com> wrote:
> > > > >
> > > > > > Ok, I added the fix to the examples. @ablanton
> > > > > > <https://github.com/ablanton> could you confirm that any of the
> > > > examples
> > > > > > would run on your phone? I don't have an iOS 9 device at hand to
> do
> > > > some
> > > > > > testing!
> > > > > >
> > > > > > You can try with this one for example :
> > > > > > http://sebpiq.github.io/WebPd/examples/phasor/
> > > > > > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831
> > >.
> > > > > >
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > >
> > > > > andrewblanton.com
> > > > >
> > > > > <http://andrewblanton.com/portfolio.html>
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701
> >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > *Sébastien Piquemal*
> > > >
> > > > -----* @sebpiq*
> > > > ----- http://github.com/sebpiq
> > > > ----- http://funktion.fm
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037845>.
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > andrewblanton.com
> > >
> > > <http://andrewblanton.com/portfolio.html>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037981>.
> >
> > >
> >
> >
> >
> > --
> >
> > *Sébastien Piquemal*
> >
> > -----* @sebpiq*
> > ----- http://github.com/sebpiq
> > ----- http://funktion.fm
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149043402>.
> >
>
>
>
> --
>
> andrewblanton.com
>
> <http://andrewblanton.com/portfolio.html>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149048920>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by ablanton** [comment]
Grrr ... Sorry, such a pain in the ass. I will say the p5 sound lib is
still working, I'm not sure what they are doing differently but this might
be of help!

On Sunday, October 18, 2015, Sebastien Piquemal <notifications@github.com>
wrote:

> Dammit ... ok I'll find a device and solve this.
>
> On Mon, Oct 19, 2015 at 12:31 AM, åπ∆®£w °ı• ß|ªπ†°n <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > unfortunately the problem persist...
> >
> >
> > On Sun, Oct 18, 2015 at 1:15 PM, Sebastien Piquemal <
> > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > No actually if it is stuck on "loading" and you don't even get the
> start
> > > button, it means it is stuck before `Pd.start` ... That is weird.
> > >
> > > What about now, is it working? If not, I'll have to get an ios9 device
> > next
> > > week, and see what's wrong ...
> > >
> > > On Sun, Oct 18, 2015 at 9:48 PM, åπ∆®£w °ı• ß|ªπ†°n <
> > >
> > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > >
> > > > yes exactly, like (and correct me if i'm wrong) it is stuck on
> > Pd.start()
> > > > on mobile and cannot proceed to load anymore of the page.
> > > >
> > > > On Sun, Oct 18, 2015 at 11:45 AM, Sebastien Piquemal <
> > > >
> > > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > >
> > > > > Oh Wait! So you mean you don't even see the "start" button? It
> > crashes
> > > on
> > > > > "loading"?
> > > > >
> > > > > On Sun, Oct 18, 2015 at 9:43 PM, åπ∆®£w °ı• ß|ªπ†°n <
> > > > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > >
> > > > > > Hi Sebastien,
> > > > > >
> > > > > > It's still getting caught on page load. It just says loading, and
> > > this
> > > > is
> > > > > > similar behavior in mobile chrome. Works well on a regular
> browser,
> > > did
> > > > > you
> > > > > > test against older versions of mobile safari?
> > > > > >
> > > > > > On Sun, Oct 18, 2015 at 10:25 AM, Sebastien Piquemal <
> > > > > > notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> > > > > >
> > > > > > > Ok, I added the fix to the examples. @ablanton
> > > > > > > <https://github.com/ablanton> could you confirm that any of
> the
> > > > > examples
> > > > > > > would run on your phone? I don't have an iOS 9 device at hand
> to
> > do
> > > > > some
> > > > > > > testing!
> > > > > > >
> > > > > > > You can try with this one for example :
> > > > > > > http://sebpiq.github.io/WebPd/examples/phasor/
> > > > > > > or this one ; http://sebpiq.github.io/WebPd/examples/delays/
> > > > > > >
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > <
> > https://github.com/sebpiq/WebPd/issues/81#issuecomment-149031831
> > > >.
> > > > > > >
> > > > > >
> > > > > >
> > > > > >
> > > > > > --
> > > > > >
> > > > > > andrewblanton.com
> > > > > >
> > > > > > <http://andrewblanton.com/portfolio.html>
> > > > > >
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037701
> > >.
> > > > > >
> > > > >
> > > > >
> > > > >
> > > > > --
> > > > >
> > > > > *Sébastien Piquemal*
> > > > >
> > > > > -----* @sebpiq*
> > > > > ----- http://github.com/sebpiq
> > > > > ----- http://funktion.fm
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037845
> >.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > >
> > > > andrewblanton.com
> > > >
> > > > <http://andrewblanton.com/portfolio.html>
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149037981>.
> > >
> > > >
> > >
> > >
> > >
> > > --
> > >
> > > *Sébastien Piquemal*
> > >
> > > -----* @sebpiq*
> > > ----- http://github.com/sebpiq
> > > ----- http://funktion.fm
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149043402>.
> > >
> >
> >
> >
> > --
> >
> > andrewblanton.com
> >
> > <http://andrewblanton.com/portfolio.html>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149048920>.
> >
>
>
>
> --
>
> *Sébastien Piquemal*
>
> -----* @sebpiq*
> ----- http://github.com/sebpiq
> ----- http://funktion.fm
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149094928>.
>


-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>

**Comment by notthetup** [comment]
@sebpiq I just tried http://sebpiq.github.io/WebPd/examples/delays/ and http://sebpiq.github.io/WebPd/examples/phasor/ on Safari on OSX, and I'm getting the following two errors..

```
[Error] InvalidStateError: DOM Exception 11: An attempt was made to use an object that is not, or is no longer, usable. - webpd-latest.js:104
[Error] ReferenceError: Can't find variable: Pd - phasor:41
```

Seems unrelated, but that could be the reason why @ablanton wasn't able to run the demos.

**Comment by notthetup** [comment]
Traced it down to `buffer.start()` being called twice within `_hasSelectiveDisconnect`.

**Comment by sebpiq** [comment]
Thanks Chnimay! I'm on it... So stupid of me not to have tested on a Webkit browser ... I am in Ubuntu so you know, I don't have that reflex :)

I think the error comes from the AudioContext monkey patch (https://github.com/cwilso/AudioContext-MonkeyPatch/blob/gh-pages/AudioContextMonkeyPatch.js)

which is bundled with WebPd. Let's see if the updated version solves this ...

**Comment by notthetup** [comment]
@sebpiq No problem. Let me know if you need me to test anything. I have an iPad here as well. Buzz me on WebAudio Slack.

**Comment by sebpiq** [comment]
Thanks a lot! I might ask you soon, cause I think there is something totally wrong on the WebKit browser I'm trying to test with ...

**Comment by sebpiq** [comment]
Anyways, this is something that shouldn't happen ... The library shouldn't break at the first API change, without anybody knowing. I've asked a free account for open source to browserstack, and hopefully they'll accept, which means that I'll run automated cross-browser tests there, and I'll be notified if anything breaks in any web browser (created an issue : #83)
Sorry @ablanton , hopefully it didn't destroy your enthusiasm in the library :)

**Comment by ablanton** [comment]
Sebastien! This is totally natural and would be no fun it there were no
issues. I love the library and really appreciate the work you guys are
doing. No, my enthusiasm is not even close to swayed :D

On Mon, Oct 19, 2015 at 1:13 AM, Sebastien Piquemal <
notifications@github.com> wrote:

> Anyways, this is something that shouldn't happen ... The library shouldn't
> break at the first API change, without anybody knowing. I've asked a free
> account for open source to browserstack, and hopefully they'll accept,
> which means that I'll run automated cross-browser tests there, and I'll be
> notified if anything breaks in any web browser (created an issue : #83
> <https://github.com/sebpiq/WebPd/issues/83>)
> Sorry @ablanton <https://github.com/ablanton> , hopefully it didn't
> destroy your enthusiasm in the library :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-149138615>.
>



-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>

**Comment by sebpiq** [comment]
Ok this should be fixed now, and examples should work! This was actually fixed back then already, but we probably got bitten by caching problems, loading old js files that still contained the bug ...

**Comment by ablanton** [comment]
Excellent, I will test soon.

On Mon, Nov 9, 2015 at 8:36 AM, Sebastien Piquemal <notifications@github.com
> wrote:

> Ok this should be fixed now, and examples should work! This was actually
> fixed back then already, but we probably got bitten by caching problems,
> loading old js files that still contained the bug ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/81#issuecomment-155116729>.
>



-- 

andrewblanton.com

<http://andrewblanton.com/portfolio.html>
