### ISSUE TITLE
It should be easy to directly connect the output of a patch to other Web Audio nodes outside of WebPd

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/WebPd#82]
for example `patch.out.connect(faustEffect)`

**Comment by meta-meta** [comment]
This is what I came here for. Glad it's on the horizon. How much thought has been put into an implementation? I wouldn't mind taking a crack at it.

**Comment by sebpiq** [comment]
This is actually pretty straightforward. This just made me think that there is a bug here which needs fixing.

**Comment by sebpiq** [comment]
done 3938dbed10d5c28c3a81fe54a9074fe943922132

See :
https://github.com/sebpiq/WebPd#connecting-a-patch-outlet-to-an-external-web-audio-node

There is still a bug if the patch has several [outlet~] objects though : https://github.com/sebpiq/pd-fileutils/issues/28

**Comment by meta-meta** [comment]
whoa that's some turnaround time! I was confused for a second when I couldn't find the issue in the open issues list. :astonished:  I spent the day getting positional audio working properly in aframe.io - next up, PD in WebVR!

**Comment by sebpiq** [comment]
Awesome :) keep me updated that sound great!!!

And beware with #93 !

**Comment by meta-meta** [comment]
well, I finally got around to trying this out. Here's my initial progress: https://meta-meta.github.io/aframe-puredata-component/basic/

two very simple PD patches loaded in a THREE.js scene!
