### ISSUE TITLE
Cross-browser automated testing

### ISSUE THREAD

**Issue by sebpiq** [sebpiq/WebPd#83]
Asked an account to browserstack, hopefully they'll accept.

**Comment by sebpiq** [comment]
saucelabs offer free testing for OSS projects. I can run tests using this : https://github.com/pbakaus/mocha-sauce

browser tests need to be slightly refactored so that they use the latest build of WebPd instead of a custom browserified version.

**Comment by mihow** [comment]
Great idea!
