### ISSUE TITLE
sending/receiving events to/from individual objects

### ISSUE THREAD

**Issue by taylorbf** [sebpiq/WebPd#84]
I see that many components of WebPd extend node's event emitter. Is it currently possible (if so, is there a best practice?) for sending messages directly to objects? For example, to set a number object's text directly -- I.e. not to send a message not a [receive] object, but directly to the number object?

Likewise, is it possible to receive updates from objects, for example a stream of events from a [line~] that is ramping?

I know using [send] and [receive] are perfectly good ways to do this now. I am looking into GUI scenarios in which I don't want to create a [receive] for each object. If not, that is fine -- just checking!

**Comment by sebpiq** [comment]
Hi Ben!

First, if you need to get an object from a patch (say, get all the toggle
objects), you could do :

```javascript
var toggles = patch.objects.filter(function(obj) { return obj.type ===
'tgl' })
```

Then to each object, you can send a message like this :

```javascript
myToggle.i(0).message(['bang'])
```

the method `Object.i(<inletId>)` returns an inlet object and the method
`Inlet.message(<args>)` sends a message to that inlet (which will then be
transmitted to the object).

To receive messages, it is slightly harder, I would recommend to create a
dummy inlet, and connect it to the outlet of the object you want to receive
messages from. For example :

```javascript
var dummyObject = {patch: patch}
    , receiver = new Pd.core.portlets.Inlet(dummyObject)

// Overwriting the message method which will be called when a message has
been sent
// by outlets upstream in the patch
receiver.message = function(args) {
    doWhateverWithArgs()
}

myToggle.o(0).connect(receiver)
```

As you can guess `Object.o(<outletId>)` returns an outlet object and
`Outlet.connect(<inlet>)` connects and outlet and an intlet, causing the
messages to be transmitted.

Now, if you want to go deeper than that, you'll have to use read teh code.
Each object has some methods which can be called directly, if for example
you want to directly set the state of an object, without going through
messages. But while the methods I detailed above are quite clean and
eventually they will be documented as a public API, most of the objects'
methods are a bit more messy, less consistent and not ready to be public.
But I believe it is not hard to read, so you can still have a look :

https://github.com/sebpiq/WebPd/blob/master/lib/objects/dsp.js
https://github.com/sebpiq/WebPd/blob/master/lib/objects/glue.js
https://github.com/sebpiq/WebPd/blob/master/lib/objects/controls.js

Hopefully this answers :)


On Wed, Oct 21, 2015 at 12:56 AM, Ben Taylor <notifications@github.com>
wrote:

> I see that many components of WebPd extend node's event emitter. Is it
> currently possible (if so, is there a best practice?) for sending messages
> directly to objects? For example, to set a number object's text directly --
> I.e. not to send a message not a [receive] object, but directly to the
> number object?
>
> Likewise, is it possible to receive updates from objects, for example a
> stream of events from a [line~] that is ramping?
>
> I know using [send] and [receive] are perfectly good ways to do this now.
> I am looking into GUI scenarios in which I don't want to create a [receive]
> for each object. If not, that is fine -- just checking!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/84>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm

**Comment by sebpiq** [comment]
Hi Ben!

First, if you need to get an object from a patch (say, get all the toggle
objects), you could do :

```javascript
var toggles = patch.objects.filter(function(obj) { return obj.type ===
'tgl' })
```

Then to each object, you can send a message like this :

```javascript
myToggle.i(0).message(['bang'])
```

the method `Object.i(<inletId>)` returns an inlet object and the method
`Inlet.message(<args>)` sends a message to that inlet (which will then be
transmitted to the object).

To receive messages, it is slightly harder, I would recommend to create a
dummy inlet, and connect it to the outlet of the object you want to receive
messages from. For example :

```javascript
var dummyObject = {patch: patch}
    , receiver = new Pd.core.portlets.Inlet(dummyObject)

// Overwriting the message method which will be called when a message has
been sent
// by outlets upstream in the patch
receiver.message = function(args) {
    doWhateverWithArgs()
}

myToggle.o(0).connect(receiver)
```

As you can guess `Object.o(<outletId>)` returns an outlet object and
`Outlet.connect(<inlet>)` connects and outlet and an intlet, causing the
messages to be transmitted.

Now, if you want to go deeper than that, you'll have to use read teh code.
Each object has some methods which can be called directly, if for example
you want to directly set the state of an object, without going through
messages. But while the methods I detailed above are quite clean and
eventually they will be documented as a public API, most of the objects'
methods are a bit more messy, less consistent and not ready to be public.
But I believe it is not hard to read, so you can still have a look :

https://github.com/sebpiq/WebPd/blob/master/lib/objects/dsp.js
https://github.com/sebpiq/WebPd/blob/master/lib/objects/glue.js
https://github.com/sebpiq/WebPd/blob/master/lib/objects/controls.js

Hopefully this answers :)

**Comment by shamansir** [comment]
Nice, this could help me as well!

**Comment by taylorbf** [comment]
Yes this worked great! Thanks for the detailed examples.

It allowed me to connect GUI components directly to the WebPd model and even receive visual feedback from the WebPd model as it changes. I've posted this work [here](http://github.com/taylorbf/pdgui).
