### ISSUE TITLE
Provide access to patch data from a patch instance

### ISSUE THREAD

**Issue by shamansir** [sebpiq/WebPd#86]
I discovered that in [pdgui](https://github.com/taylorbf/pdgui) example Ben injected (I suppose) his own method named [`Pd.getPatchData`](https://github.com/taylorbf/pdgui/blob/master/js/webpd-latest.js#L331) to get access to a result of `pdfu.parse` and not to re-include `pdfu` itself since it's already securely stored inside `WebPd`. 

I think it would be useful to be able to get access to this data (i.e. connections and nodes) from the instance created with `Pd.loadPatch`, because this data is required to build UI without re-parsing the file second time. Something optional, like `patch.tree` or `patch.json` or `patch.data`, whatever you like. 

This would be used this way:

```javascript
var patch = Pd.loadPatch(file_contents);
patch.data.connections.forEach(function(node) { /* ... */ });
patch.data.nodes.forEach(function(node) { /* ... */ });
```

**Comment by shamansir** [comment]
...or may be there's some easy access to `pdfu` from `Pd` object I haven't noticed.

**Comment by shamansir** [comment]
Done this in shamansir/WebPd@3ed8936

**Comment by sebpiq** [comment]
Hi Anton! Thanks for this. I merged, but I renamed `getPatchData` to `parsePatch`

**Comment by shamansir** [comment]
Great, thank you!
