### ISSUE TITLE
Easier way to know if intel/outlet is DSP kind

### ISSUE THREAD

**Issue by shamansir** [sebpiq/WebPd#89]
This is secondary, I suppose, but in my case [I am required](https://github.com/shamansir/rpd/commit/b6347d873383bcdfa437c4047235f0b0b5c96e50#diff-7531f3c46121c9428788ed2ba533a3beR218) to check `prototype` of the items from `inletDefs`/`outletDefs`, to know if inlet/outlet is really `DspInlet`/`DspOutlet`.

It's ok just to check for equality to `Pd.core.portlets.DspInlet`/`Pd.core.portlets.DspOutlet` in most cases, but i.e. for `phasor~` it doesn't work, since equality changes with `DspInlet.extend`.

So, for now, to know if inlet/outlet in library definition is DSP, I have to do double-check:

```javascript
function isDspInletDef(def) {
    return (def === DspInlet) ||
           (def.prototype && (def.prototype instanceof DspInlet));
}

function isDspOutletDef(def) {
    return (def === DspOutlet) ||
           (def.prototype && (def.prototype instanceof DspOutlet));
}

...

var inletDefs  = library[command].prototype.inletDefs,
    outletDefs = library[command].prototype.outletDefs;
if (isDspInletDef(inletDefs[i])) { ... }
if (isDspOutletDef(outletDefs[i])) { ... }
```

**Comment by shamansir** [comment]
I've realized that in my case I don't need library at all and I may use what `createObject` returned for this node also for inlet/outlet count/types etc., and so other users should prefer that way too. `instanceof` should work for inlet/outlet instances. Invalid.

**Comment by sebpiq** [comment]
Yes, I think this is a better approach. I was also wondering why you need
library (appart from listing available objects)

On Mon, Nov 30, 2015 at 3:30 AM, Ulric Wilfred <notifications@github.com>
wrote:

> I've realized that in my case I don't need library at all and I may use
> what createObject returned for this node also for inlet/outlet
> count/types etc., and so other users should prefer that way too.
> instanceof should work for inlet/outlet instances. Invalid.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/89#issuecomment-160493445>.
>



-- 

*Sébastien Piquemal*

 -----* @sebpiq*
 ----- http://github.com/sebpiq
 ----- http://funktion.fm
