### ISSUE TITLE
Sending default dollar-value from message node

### ISSUE THREAD

**Issue by shamansir** [sebpiq/WebPd#90]
Hi! I am not sure if it's a bug, may be I just need an advice.

The phasor example below has a message node, which has `$1 1000` in it. In PD's Edit Mode, by default, if you click this message with attached `print` node, it will print out `print 0 1000`. I see there is [some resolver](https://github.com/sebpiq/WebPd/blob/fe9d61d7f2f672986727af9c56a7330018d02b06/lib/glue.js#L102) in the message node inlet, and it substitutes dollar-values with actual ones quite well, but by default `this.obj.resolver(['$1', 1000])` is yet `["$1", 1000]`, instead of (I suppose) `[0, 1000]`. Is that right?

The example:

```
#N canvas 511 225 762 387 10;
#X obj 127 161 dac~;
#X obj 128 101 line~;
#X obj 128 40 loadbang;
#X msg 128 71 220;
#X msg 199 70 \$1 1000;
#X obj 199 40 r freq;
#X obj 128 130 phasor~;
#X obj 231 117 print;
#X obj 368 210 s freq;
#X floatatom 353 140 5 0 0 0 - - -;
#X connect 1 0 6 0;
#X connect 2 0 3 0;
#X connect 3 0 1 0;
#X connect 4 0 1 0;
#X connect 4 0 7 0;
#X connect 5 0 4 0;
#X connect 6 0 0 0;
#X connect 6 0 0 1;
#X connect 9 0 8 0;
```

**Comment by shamansir** [comment]
I managed to get it working it in my model with fixing message flow between nodes in shamansir/rpd#240. Resolving logic is correct in my case. Sorry for one more invalid issue.

**Comment by sebpiq** [comment]
no worries :) better invalid issues that issues that go unnoticed!
