### ISSUE TITLE
examples won't work on iPhone in iOS 9.1

### ISSUE THREAD

**Issue by 821760408-sp** [sebpiq/WebPd#91]
The latest WebPd won't work on iPhone in iOS 9.1--it stuck on "Loading.." in both Chrome and Safari.

It works on my iPad running iOS 8.4, so my guess it's an iOS version issue?

**Comment by sebpiq** [comment]
oooh ... I thought all was fixed with iOS :((
I can't really debug, as I don't have a device myself, which makes things really complicated. I'll try to get this fixed asap. But without help it'll probably take couple of weeks before I can get my hand on a test device.

**Comment by sebpiq** [comment]
Hey I have tried with online emulator (saucelabs) on iOS 9.1 , and it seems to work passed "loading". The emulator doesn't support sound, so I can't hear whether this actually works or not, but at least it manages to load properly. Have you tried all examples? Have you tried cleaning your browser cache (that could be the problem if you have tried WebPd examples before I fixed them about a month ago) ?

**Comment by 821760408-sp** [comment]
I tried cleaning my browser cache and that didn't help. I also tried using different iPhones (5 & 6 plus) on iOS 9.1 and those won't work either. The iPhones that didn't work were running AppleWebKit/601.1.16 and were stuck on loading pd files, while the iPad that worked were running AppleWebKit/600.1.4

**Comment by sebpiq** [comment]
Ah :/ no luck. It was worth trying!
So yeah ... I'll fix that but I need a device first. iOS has really been a troublemaker.

**Comment by grav** [comment]
Works on my iPhone 6 running iOS 9.3.2

**Comment by sebpiq** [comment]
Yes I have seen it working on ios 9.2 too ... I guess I was just waiting for a confirmation. I'lt close the issue now.
