### ISSUE TITLE
Invalid [line~] duration

### ISSUE THREAD

**Issue by caltivan** [sebpiq/WebPd#94]
Hi
I have been trying to use the webpd with the patch that i created for android and i get the error:
Invalid [line~] duration when i'm doing the instruction.

var patch
        $.get('patches/player_C3.pd', function(patchStr) {
          patch = Pd.loadPatch(patchStr)
          Pd.start()
          //webPdExamples.patchLoaded(patchStr);
          console.log(patch);
          Pd.send('loadNotesC3',['bang']);
          //Pd.send('playNoteC3',['bang']);

```
    })
```

This is the pd that im try to run
![image](https://cloud.githubusercontent.com/assets/358089/13730671/361b45d4-e923-11e5-9d43-d0383e019dc6.png)

i checked the list of supported pd objects and im using the supported ones, so i dont ge it how to run the patch.

Thanks
Regards

**Comment by sebpiq** [comment]
Hi @caltivan! And sorry for the super slow answer... Could you please send me the patch, so I can have a look?

**Comment by caltivan** [comment]
Hi

Im attaching the patch

Thanks for the help

Regars

2016-03-31 5:04 GMT-05:00 Sebastien Piquemal <notifications@github.com>:

**Comment by sebpiq** [comment]
oops, closed by mistake

**Comment by sebpiq** [comment]
hey @caltivan any chance you could resend the patch? Maybe open it and paste it either here or somewhere online. Thanks!!!

**Comment by caltivan** [comment]
Hi
sorry i have re attach the patch

Regards

2016-04-26 9:44 GMT-05:00 Sebastien Piquemal <notifications@github.com>:

**Comment by sebpiq** [comment]
@caltivan if you're sending the patch as an email attachment it won't go through. You need to paste it somewhere or send it to my email directly sebpiq@gmail.com
