### ISSUE TITLE
Firefox "event expired"

### ISSUE THREAD

**Issue by Drumaddict182** [sebpiq/WebPd#98]
Hello everyone, 

Since the last update of Firefox i have the message "event expired" for the Webpd script and i don't have any sound from my Pure Data Patches. 

Someone has the same problem ? Someone know a solution for this issue ? 

Thanx. 

![webpd_error](https://cloud.githubusercontent.com/assets/18629243/14761092/7f7dc64a-0956-11e6-91e3-aba85831de55.jpg)

**Comment by sebpiq** [comment]
Yes indeed ... same problem here. I will fix it asap

**Comment by sebpiq** [comment]
It would help also if you could send me your patch please!

**Comment by Drumaddict182** [comment]
Hi thanks very much for the answer.

Here are my three patches i'm using in my website.



2016-04-25 18:07 GMT+02:00 Sebastien Piquemal <notifications@github.com>:

> It would help also if you could send me your patch please!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/sebpiq/WebPd/issues/98#issuecomment-214420651>
>



-- 
Alexis MATTON
Sound Designer Freelance
http://alexismatton.com/

#N canvas 0 0 1676 967 10;
#X obj 120 400 osc~ 528;
#X obj 120 197 *~;
#X obj 493 400 osc~ 44;
#X obj 307 468 +~;
#X obj 1089 921 dac~;
#X obj 120 333 +~ 30;
#X obj 493 333 +~ 30;
#X obj 120 265 *~ 20;
#X obj 493 197 osc~ 15;
#X obj 493 265 *~ 500;
#X obj 652 50 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 1
1;
#X obj 638 134 f 1;
#X obj 689 135 + 1;
#X obj 641 188 / 100;
#X obj 638 231 sin;
#X obj 639 267 + 1;
#X obj 638 305 * 100;
#X obj 635 341 + 300;
#X floatatom 654 374 5 0 0 0 - - -;
#X obj 640 427 hsl 128 15 200 600 0 0 empty empty empty -2 -8 0 10
-262144 -1 -1 7064 1;
#X obj 295 658 loadbang;
#X msg 301 777 \; pd dsp 1;
#X obj 774 53 loadbang;
#X obj 434 546 bp~ 300 10;
#X obj 953 536 osc~ 484;
#X obj 1023 467 osc~ 528;
#X obj 883 331 osc~ 3.3;
#X obj 953 399 *~;
#X obj 1023 331 sig~ 1;
#X obj 1303 331 osc~ 9.6;
#X obj 1416 339 osc~ 3.8;
#X obj 1373 399 *~;
#X obj 1163 467 *~;
#X obj 1093 536 *~;
#X obj 1023 604 *~;
#X obj 1163 604 osc~ 2.6;
#X obj 1093 672 *~;
#X obj 1233 672 osc~ 220;
#X obj 344 505 *~ 0.1;
#X obj 757 692 line~;
#X msg 690 628 10 200;
#X msg 761 630 1 2500;
#X obj 776 600 del 200;
#X obj 889 562 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 714 560 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X msg 798 573 stop;
#X obj 833 516 delay 5000;
#X obj 699 480 metro 10000;
#X msg 837 638 0 1000;
#X obj 1164 778 *~;
#X obj 1029 809 *~ 0.5;
#X obj 1164 741 *~;
#X obj 1705 409 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 1922 387 metro 10000;
#X obj 1372 545 + 100;
#X obj 1511 560 + 100;
#X obj 2126 715 line~;
#X msg 2059 651 10 200;
#X msg 2130 653 1 2500;
#X obj 2145 623 del 200;
#X obj 2258 585 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 2083 583 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X msg 2167 596 stop;
#X obj 2202 539 delay 5000;
#X msg 2206 661 0 1000;
#X obj 1679 844 *~;
#X obj 1368 648 osc~ 1;
#X obj 1507 663 osc~ 1;
#X obj 1663 555 + 100;
#X obj 1659 658 osc~ 1;
#X obj 1376 483 random 500;
#X obj 1515 499 random 500;
#X obj 1667 494 random 500;
#X obj 1505 256 delay 3000;
#X obj 1134 834 *~ 0.3;
#X obj 1519 771 *~ 0.05;
#X obj 643 91 metro 25;
#X obj 29 129 osc~ 1.6;
#X obj 213 128 osc~ 3.8;
#X obj 549 744 line~;
#X obj 1056 862 *~;
#X msg 525 680 1 2000;
#X obj 1127 872 *~;
#X connect 0 0 3 0;
#X connect 1 0 7 0;
#X connect 2 0 3 1;
#X connect 3 0 38 0;
#X connect 5 0 0 0;
#X connect 6 0 2 0;
#X connect 7 0 5 0;
#X connect 8 0 9 0;
#X connect 9 0 6 0;
#X connect 10 0 76 0;
#X connect 11 0 12 0;
#X connect 11 0 13 0;
#X connect 12 0 11 1;
#X connect 13 0 14 0;
#X connect 14 0 15 0;
#X connect 15 0 16 0;
#X connect 16 0 17 0;
#X connect 17 0 18 0;
#X connect 17 0 23 1;
#X connect 18 0 19 0;
#X connect 20 0 21 0;
#X connect 22 0 10 0;
#X connect 22 0 47 0;
#X connect 22 0 73 0;
#X connect 22 0 81 0;
#X connect 23 0 50 0;
#X connect 24 0 34 0;
#X connect 25 0 33 0;
#X connect 26 0 27 0;
#X connect 27 0 32 0;
#X connect 28 0 27 1;
#X connect 29 0 31 0;
#X connect 30 0 31 1;
#X connect 31 0 32 1;
#X connect 32 0 33 1;
#X connect 33 0 34 1;
#X connect 34 0 36 0;
#X connect 35 0 36 1;
#X connect 36 0 51 0;
#X connect 37 0 51 1;
#X connect 38 0 23 0;
#X connect 39 0 49 1;
#X connect 40 0 39 0;
#X connect 41 0 39 0;
#X connect 42 0 41 0;
#X connect 43 0 48 0;
#X connect 43 0 45 0;
#X connect 44 0 40 0;
#X connect 44 0 41 0;
#X connect 45 0 42 0;
#X connect 46 0 43 0;
#X connect 47 0 44 0;
#X connect 47 0 46 0;
#X connect 48 0 39 0;
#X connect 49 0 74 0;
#X connect 50 0 80 0;
#X connect 51 0 49 0;
#X connect 52 0 70 0;
#X connect 52 0 71 0;
#X connect 52 0 72 0;
#X connect 53 0 52 0;
#X connect 53 0 63 0;
#X connect 53 0 61 0;
#X connect 54 0 66 0;
#X connect 55 0 67 0;
#X connect 56 0 65 1;
#X connect 57 0 56 0;
#X connect 58 0 56 0;
#X connect 59 0 58 0;
#X connect 60 0 64 0;
#X connect 60 0 62 0;
#X connect 61 0 57 0;
#X connect 61 0 58 0;
#X connect 62 0 59 0;
#X connect 63 0 60 0;
#X connect 64 0 56 0;
#X connect 65 0 4 1;
#X connect 66 0 75 0;
#X connect 67 0 75 0;
#X connect 68 0 69 0;
#X connect 69 0 75 0;
#X connect 70 0 54 0;
#X connect 71 0 55 0;
#X connect 72 0 68 0;
#X connect 73 0 53 0;
#X connect 74 0 82 0;
#X connect 75 0 65 0;
#X connect 76 0 11 0;
#X connect 77 0 1 0;
#X connect 78 0 1 1;
#X connect 79 0 80 1;
#X connect 79 0 82 1;
#X connect 80 0 4 0;
#X connect 80 0 4 1;
#X connect 81 0 79 0;
#X connect 82 0 4 0;

#N canvas 0 0 1668 967 10;
#X obj 415 152 random 7;
#X obj 414 189 sel 0 1 2 3 4 5 6;
#X msg 378 235 0;
#X msg 429 237 2;
#X msg 484 237 3;
#X msg 539 236 5;
#X msg 585 239 7;
#X msg 641 243 8;
#X msg 683 240 10;
#X floatatom 480 319 5 0 0 0 - - -;
#X obj 472 436 mtof;
#X floatatom 470 476 5 0 0 0 - - -;
#X obj 473 513 sig~;
#X obj 478 564 osc~;
#X obj 908 892 dac~;
#X obj 643 601 line~;
#X obj 662 509 del 200;
#X obj 802 477 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 600 469 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X msg 684 482 stop;
#X obj 489 600 *~;
#X msg 579 537 10 200;
#X obj 719 425 delay 50;
#X obj 416 28 loadbang;
#X msg 653 45 \; pd dsp 1;
#X obj 170 203 random 500;
#X obj 396 107 metro 5000;
#X obj 200 142 metro 500;
#X msg 723 547 0 1000;
#X floatatom 688 702 4 0 999 0 - - -;
#X obj 725 738 delread~ delay1;
#X obj 576 652 *~ 0.3;
#X obj 198 288 + 4000;
#X obj 480 380 + 60;
#X obj 1005 134 random 7;
#X obj 1004 171 sel 0 1 2 3 4 5 6;
#X msg 968 217 0;
#X msg 1019 219 2;
#X msg 1074 219 3;
#X msg 1129 218 5;
#X msg 1175 221 7;
#X msg 1231 225 8;
#X msg 1273 222 10;
#X floatatom 1070 301 5 0 0 0 - - -;
#X obj 1062 418 mtof;
#X floatatom 1060 458 5 0 0 0 - - -;
#X obj 1063 495 sig~;
#X obj 1068 546 osc~;
#X obj 1233 583 line~;
#X obj 1252 491 del 200;
#X obj 1392 459 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X obj 1190 451 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144
-1 -1;
#X msg 1274 464 stop;
#X obj 1079 582 *~;
#X msg 1169 519 10 200;
#X obj 1255 405 delay 50;
#X obj 1012 42 loadbang;
#X obj 760 185 random 500;
#X obj 986 89 metro 5000;
#X obj 790 124 metro 500;
#X msg 1313 529 0 1000;
#X floatatom 1279 684 4 0 999 0 - - -;
#X obj 1166 634 *~ 0.3;
#X obj 1070 362 + 60;
#X obj 271 88 delay 2000;
#X obj 867 77 delay 2200;
#X obj 631 835 line~;
#X obj 846 833 *~;
#X msg 649 539 1 50;
#X msg 1237 521 1 50;
#X obj 1316 720 delread~ delay2;
#X obj 475 653 *~ 0.1;
#X obj 1065 635 *~ 0.1;
#X msg 607 771 1 5000;
#X obj 790 270 + 5000;
#X msg 1166 679 1000;
#X msg 576 697 1000;
#X obj 710 654 delwrite~ delay1 2000;
#X obj 1300 636 delwrite~ delay2 2000;
#X connect 0 0 1 0;
#X connect 1 0 2 0;
#X connect 1 1 3 0;
#X connect 1 2 4 0;
#X connect 1 3 5 0;
#X connect 1 4 6 0;
#X connect 1 5 7 0;
#X connect 1 6 8 0;
#X connect 2 0 9 0;
#X connect 3 0 9 0;
#X connect 4 0 9 0;
#X connect 5 0 9 0;
#X connect 6 0 9 0;
#X connect 7 0 9 0;
#X connect 8 0 9 0;
#X connect 9 0 33 0;
#X connect 10 0 11 0;
#X connect 11 0 12 0;
#X connect 12 0 13 0;
#X connect 13 0 20 0;
#X connect 15 0 20 1;
#X connect 16 0 68 0;
#X connect 17 0 28 0;
#X connect 17 0 19 0;
#X connect 18 0 21 0;
#X connect 18 0 68 0;
#X connect 19 0 16 0;
#X connect 20 0 71 0;
#X connect 21 0 15 0;
#X connect 22 0 17 0;
#X connect 23 0 24 0;
#X connect 23 0 76 0;
#X connect 23 0 64 0;
#X connect 25 0 32 0;
#X connect 26 0 0 0;
#X connect 26 0 22 0;
#X connect 26 0 18 0;
#X connect 27 0 25 0;
#X connect 28 0 15 0;
#X connect 29 0 30 0;
#X connect 30 0 67 0;
#X connect 31 0 77 0;
#X connect 32 0 26 1;
#X connect 33 0 10 0;
#X connect 34 0 35 0;
#X connect 35 0 36 0;
#X connect 35 1 37 0;
#X connect 35 2 38 0;
#X connect 35 3 39 0;
#X connect 35 4 40 0;
#X connect 35 5 41 0;
#X connect 35 6 42 0;
#X connect 36 0 43 0;
#X connect 37 0 43 0;
#X connect 38 0 43 0;
#X connect 39 0 43 0;
#X connect 40 0 43 0;
#X connect 41 0 43 0;
#X connect 42 0 43 0;
#X connect 43 0 63 0;
#X connect 44 0 45 0;
#X connect 45 0 46 0;
#X connect 46 0 47 0;
#X connect 47 0 53 0;
#X connect 48 0 53 1;
#X connect 49 0 69 0;
#X connect 50 0 60 0;
#X connect 50 0 52 0;
#X connect 51 0 54 0;
#X connect 51 0 69 0;
#X connect 52 0 49 0;
#X connect 53 0 72 0;
#X connect 54 0 48 0;
#X connect 55 0 50 0;
#X connect 56 0 75 0;
#X connect 56 0 65 0;
#X connect 57 0 74 0;
#X connect 58 0 34 0;
#X connect 58 0 55 0;
#X connect 58 0 51 0;
#X connect 59 0 57 0;
#X connect 60 0 48 0;
#X connect 61 0 70 0;
#X connect 62 0 78 0;
#X connect 63 0 44 0;
#X connect 64 0 27 0;
#X connect 64 0 26 0;
#X connect 64 0 73 0;
#X connect 65 0 59 0;
#X connect 65 0 58 0;
#X connect 66 0 67 1;
#X connect 67 0 14 0;
#X connect 67 0 14 1;
#X connect 68 0 15 0;
#X connect 69 0 48 0;
#X connect 70 0 67 0;
#X connect 71 0 31 0;
#X connect 71 0 67 0;
#X connect 72 0 62 0;
#X connect 72 0 67 0;
#X connect 73 0 66 0;
#X connect 74 0 58 1;
#X connect 75 0 61 0;
#X connect 76 0 29 0;

#N canvas 0 0 1668 967 10;
#X obj 84 80 noise~;
#X obj 83 118 *~ 0.8;
#X obj 82 207 *~ 0.8;
#X obj 261 36 f 1;
#X obj 312 37 + 1;
#X obj 264 90 / 100;
#X obj 261 133 sin;
#X obj 262 169 + 1;
#X obj 261 207 * 100;
#X obj 258 243 + 300;
#X floatatom 277 276 5 0 0 0 - - -;
#X obj 263 329 hsl 128 15 200 600 0 0 empty empty empty -2 -8 0 10
-262144 -1 -1 3176 1;
#X obj 501 197 loadbang;
#X msg 507 316 \; pd dsp 1;
#X obj 387 -32 loadbang;
#X obj 87 314 hsl 128 15 0 1 0 0 empty empty empty -2 -8 0 10 -262144
-1 -1 0 1;
#X floatatom 461 160 5 0 0 0 - - -;
#X obj 266 -7 metro;
#X obj 81 166 bp~ 300 10;
#X floatatom 526 157 5 0 0 0 - - -;
#X obj 745 691 dac~;
#X msg 604 122 5;
#X obj 770 437 line~;
#X msg 746 373 1 2000;
#X obj 698 524 *~;
#X obj 492 71 random 20;
#X obj 494 112 moses 5;
#X obj 487 39 metro 5000;
#X connect 0 0 1 0;
#X connect 1 0 18 0;
#X connect 2 0 24 0;
#X connect 3 0 4 0;
#X connect 3 0 5 0;
#X connect 4 0 3 1;
#X connect 5 0 6 0;
#X connect 6 0 7 0;
#X connect 7 0 8 0;
#X connect 8 0 9 0;
#X connect 9 0 10 0;
#X connect 9 0 18 1;
#X connect 10 0 11 0;
#X connect 12 0 13 0;
#X connect 14 0 21 0;
#X connect 14 0 23 0;
#X connect 14 0 27 0;
#X connect 14 0 17 0;
#X connect 15 0 2 1;
#X connect 17 0 3 0;
#X connect 18 0 2 0;
#X connect 19 0 17 1;
#X connect 21 0 19 0;
#X connect 22 0 24 1;
#X connect 23 0 22 0;
#X connect 24 0 20 0;
#X connect 24 0 20 1;
#X connect 25 0 26 0;
#X connect 26 0 16 0;
#X connect 26 1 19 0;
#X connect 27 0 25 0;

**Comment by sebpiq** [comment]
I didnt receive them!

**Comment by Drumaddict182** [comment]
Sorry. Is it good now ? 

[patches.zip](https://github.com/sebpiq/WebPd/files/234995/patches.zip)

**Comment by sebpiq** [comment]
Ok, I believe it should be fixed now. Could you please try with the latest build https://raw.githubusercontent.com/sebpiq/WebPd/master/dist/webpd-latest.js and tell me if things seem to be working now? Thanks!

**Comment by Drumaddict182** [comment]
It works ! You are a hero ! 
Thanks you so much.

**Comment by sebpiq** [comment]
Yeeeeey!!! You're welcome :)
